apiVersion: v1
kind: Service
metadata:
  name: ci-cd-final-service
  labels:
    app: ci-cd-final
spec:
  type: NodePort
  selector:
    app: ci-cd-final
  ports:
    - name: http
      port: 3000        # puerto dentro del cluster
      targetPort: 3000  # puerto del contenedor
      nodePort: 30080   # NodePort expuesto por Minikube (entre 30000-32767)
